DEVICE: cuda
INPUT_BASE: /projects/datashare/dso/Cifar-10
OUTPUT_BASE: /groups/dso/bahadir/master_thesis_code/cifar_kaggle/outputs
RUN_NAME: s0_ADAM_False_6
TASK: cifar
VERSION: '0.1'
backends: false
best_accuracy: 0.0
lr: 0.01
max_epochs: 300
model_name: PreActResNet18
momentum: 0.9
nesterov: true
num_classes: 10
num_workers: 1
optimizer: ADAM
patience: 100
resume: false
scheduler: CosineAnnealingLR
seed: 0
start_epoch: 0
test_batch_size: 128
tr_batch_size: 128
weight_decay: 0.0005
