DEVICE: cuda
INPUT_BASE: not_used
OUTPUT_BASE: task2/outputs
RUN_NAME: s314_ADAM_false_3
TASK: SDNET 2018 Concrete Crack Detection
VERSION: '0.1'
backends: false
best_accuracy: 0.0
lr: 0.001
max_epochs: 50
model_name: Mobilenet_v3_large
momentum: 0.9
nesterov: true
num_classes: 2
num_workers: 1
optimizer: ADAM
patience: 100
resume: false
scheduler: lrdecay
seed: 314
start_epoch: 0
test_batch_size: 1
tr_batch_size: 256
weight_decay: 0.0005
